# Generated by Django 5.2.6 on 2026-09-18 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_used_on', models.DateField(verbose_name='前回使用日')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='本日の使用回数')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_left_alert', models.BooleanField(default=True, verbose_name='残り時間通知')),
                ('alert_interval', models.PositiveIntegerField(choices=[(5, '5分'), (10, '10分'), (15, '15分'), (30, '30分')], default=15, verbose_name='お知らせ間隔（分）')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('start_at', models.DateTimeField(verbose_name='開始予定時刻')),
                ('end_at', models.DateTimeField(verbose_name='終了予定時刻')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('start_at__gt', models.F('start_at'))), name='end_at_after_start_at')],
            },
        ),
    ]
